sansecio/magevulndb

debian/changelog, debian/control, debian/magento-module-blacklist.install, debian/magevulndb.install
to match with https://github.com/gwillem/magevulndb/commit/430121bd13931ecbecddd4a082c8f24de2993c1b
=> rename packaging to magevulndb

README.md
Swapped single and double quotes to fix #16
=> Fix #16: "No magerun installed?" oneliner

src/ModuleBlacklist/Magerun/standalone-module-scan.php
csv has been fetched with old github url. As I don't know how long github will save this url, it's better to use the new one
=> use new gitrepo name for getting the csv

magento1-vulnerable-extensions.csv
Add module with SQL injection vulnerability used in wild I have a log of new admin user being inserted via this modue.
=> Add CommerceLab_News

src/ModuleBlacklist/Magerun2/SecurityScanCommand.php
With this module enabled, the running of `magerun2` outside a Magento root, throws a warning, because this module already calls upon the M2 code in its constructor. This PR refactors things so that M2 classes are only called upon once we know that the `magerun2` command is executed within the M2 root.
=> Magerun2 fails outside of Magento 2

magento1-vulnerable-extensions.csv
FYI the vulnerability is post-auth stored XSS (I'm the reporter).
=> Add Facebook_AdsExtension

magento1-vulnerable-extensions.csv
Please see https://xn--gran-8qa.fi/magento-1-netreviews-avisverifies-security-flaw/ for the context.
Other related issues and PRs:
#22 #18 
Closes #22
Closes #18
=> Netreviews/Avisverifies Security Flaw

README.md
A suboptimal solution, but better than nothing.
=> Update procedure for non-standard version numbers.

magento1-vulnerable-extensions.csv
Please see https://marketplace.magento.com/raveinfosys-raveinfosys-deleteorder.html#product.info.details.release_notes
=> Raveinfosys_Deleteorder got fixed in 1.1.3

magento2-vulnerable-extensions.csv
See https://mirasvit.com/docs/module-gift-registry/current/changelog
=> updated vulnerable Mirasvit_Giftr version

magento2-vulnerable-extensions.csv
Added Cardgate_Payment XSS issue.
Cardgate.com noticed (webform, telephone) more then 30 days ago, no response, no fix.
=> Added Cardgate_Payment XSS issue.

magento1-vulnerable-extensions.csv
- AW blog about it 404's
- @kalpmehta published another vuln in minor version http://ka.lpe.sh/2016/11/17/multiple-security-vulnerabilities-aheadworks-follow-up-email-extension/
=> Updated AW_Followupemail

magento2-vulnerable-extensions.csv
> 2.12.14 - Oct 23, 2019:
Fix we resolved XSS vulnerability on category pages with Canonical enabled
=> updated vulnerable Amasty_Shopby version

magento2-vulnerable-extensions.csv
More information can be found at https://xn--gran-8qa.fi/bss-multiwishlist-xss-injection/ after given 3 days to vendor has passed. I have provided them also a fix for this issue, so it's just a matter of releasing a patching version. Fixing version will be added, when known is available.
I'm requesting this to be added on the list.
Reference for BSS: 17573.
=> Blacklist Bss_MultiWishlist (CWE-79)

magento2-vulnerable-extensions.csv
https://www.mageplaza.com/releases/layered-navigation/
=> Add fixed version for Mageplaza_LayeredNavigation

magento2-vulnerable-extensions.csv
Hey,
Just adding in a few vulns (stored XSS mostly) I've found in some web form extensions.
The reference blog post / URL will be live later tonight or tomorrow at some point, will comment when its live.
=> Couple of vulnerabilities in webform extensions

magento2-vulnerable-extensions.csv
Added Stripe Payments module XSS vulnerability found in all versions prior to 1.8.8
https://marketplace.magento.com/stripe-stripe-payments.html
=> Added Stripe Payments XSS vulnerability

magento2-vulnerable-extensions.csv
added wyomind pointofsale extension to the list
=> Added vulnerable extension entry

magento2-vulnerable-extensions.csv
See https://mirasvit.com/docs/module-cache-warmer/current/changelog#1-3-35:
> Fixed potential XSS issue (#249)
=> Add Mirasvit_CacheWarmer

magento2-vulnerable-extensions.csv
See https://www.sellxed.com/shop/en/eur/software/changelog/index/magento-s-internetkasse-zahlungs-extension.html:
=> Add Customweb_InternetkasseCw@4.0.339

magento2-vulnerable-extensions.csv
From the Amasty website.
" 2.6.0 - Feb 22, 2021:
Improvement we improved the security of the anonymization process and downloading of customer information as well"
I reported the issue to them and characterizing the change as an "improvement" is quite the spin on things (going to refrain from going into detail publicly on what the issue actually was)
=> Add Amasty_Gdpr < 2.6.0

magento2-vulnerable-extensions.csv
Added Klaviyo Reclaim now that the fix is available
See this statement https://gist.github.com/JeroenBoersma/f5864a45e3df63b198a57abdff366df2
=> Added Klaviyo_Reclaim < 3.0.0

magento2-vulnerable-extensions.csv
It is possible to do a DOS and PII request, still need to finish the write-up, both latest major versions are patched!
=> Added Adyen payment < 7.3.5 and < 8.1.1

magento2-vulnerable-extensions.csv
=> Fixed endpoint for adyen vulnerability

magento2-vulnerable-extensions.csv
Fixes #93 
https://aheadworks.com/layered-navigation-extension-for-magento-2#changelog
=> Add Aheadworks_Layerednav

magento1-vulnerable-extensions.csv
Sendinblue M1 plugin SQL injection vulnerability
Closes #96
=> Add Sendinblue_Sendinblue to M1 list

magento2-vulnerable-extensions.csv
https://sansec.io/research/rekoobe-fishpig-magento
=> Fishpig appears hacked

magento2-vulnerable-extensions.csv
Based on correspondence between vendor and ioweb.gr
=> Add fixed version number for BlueFormBuilder_Core

magento2-vulnerable-extensions.csv
Per: https://commercemarketplace.adobe.com/rocketweb-module-google-shopping.html
> - Security fix around feed logs, moved to var/log folder
=> Document Rocketweb vuln

magento2-vulnerable-extensions.csv
https://commercemarketplace.adobe.com/miniorange-inc-idpsaml.html#:~:text=3.0.0
```
Critical/High Severity Fixes:
1. Missing CSRF Protection - The previous version had NO CSRF protection on authentication endpoints (Token.php, Userinfo.php, IdpObserver.php). This could allow attackers to perform actions on behalf of authenticated
users.
2. Open Redirect Vulnerability - The addition of oauthserver_server_sso_validate_redirectUrl() suggests the previous version didn't validate redirect URLs, allowing attackers to redirect users to malicious sites after
authentication.
3. Token Validation Bypass - The extensive new validation methods for OAuth tokens, authorization codes, and client credentials suggest these weren't properly validated before, potentially allowing:
- Unauthorized access using …
```
=> add MiniOrange_IDPSaml
