sansecio/magevulndb

README.md, src/ModuleBlacklist/Magerun/SecurityScanCommand.php, src/ModuleBlacklist/Magerun/standalone-module-scan.php
We like to run security checks in our automated builds and fail them when any potential problems are found.
This pull request adds different exit codes depending on the scan result:
* `0` - no known vulnerabilities found
* `1` - vulnerabilities found
* `2` - could not load the CSV data (n98-magerun module only)
One then can decide in their builds whether they want to respect the exit code and fail/stop the build or ignore it.
=> Set exit code depending on result

README.md, src/ModuleBlacklist/Magerun/SecurityScanCommand.php
Per https://github.com/gwillem/magevulndb/pull/11#issuecomment-457864143 and https://github.com/gwillem/magevulndb/issues/20#issuecomment-466118694: Checking frontnames against those on installed modules would be useful in cases where we don't know what module a given frontname actually corresponds to. This will let us add suspicious routes from probes (#8, #20), and detect on those routes, without knowing further information on the modules in advance. In many cases the modules in question will be significantly out of date or used on a relatively small number of stores. It may also help with data collection by encouraging anyone running them to get in touch.
The original magerun script was pretty small and clean, but adding this code made it the opposite of small and clean, so I …
=> Refactored MageRun plugin; added frontname route checking for unknown modules.

magento1-vulnerable-extensions.csv
I found a security issue in the AheadWorks Automatic Related Products module where you can inject SQL. I tested it on multiple Magento installations and multiple versions of this module (since 2.4.2 released at least 4.5 years ago) including the latest version (2.5.0).
I reported this issue to AheadWorks. Once AheadWorks releases a patched version I will add it's version number and change the url for upgrade instructions.
=> Added AW_Autorelated - SQL injection

magento1-vulnerable-extensions.csv
I found a security issue with (I think) all of the import / export modules from Commerce Extensions a while back. The modules we used where fixed by them and I guess so did the rest but they got the same version number witch means I can not give a version number where they where fixed. I only had access to the two modules that I listed here but there are lots more and I'm almost sure they all had the same issue (see https://www.commerceextensions.com/magento-extensions.html). I can guess the module names and front names for them but am not 100% sure so I did not add them. 
I don't know if I have to make an issue for this but if any of you have access to more import / export modules from this module maker please check if the same issue exist and report the module names and front names …
=> Added Commerce Extensions import / export modules

magento1-vulnerable-extensions.csv
Discovered by @avstudnitz. Actual abuse observed.
Vuln version: 2.1.1
Vuln code:
```
$zipcode = $this->getRequest()->getParam('zipcode', false);
$country = $this->getRequest()->getParam('country', false);  
$this->_connectionRead = Mage::getSingleton('core/resource')->getConnection('core_read');
$sqlResults = $this->_connectionRead->fetchAll("SELECT city_name as placeName FROM " . Mage::getSingleton('core/resource')->getTableName('socolissimo_cities') . " WHERE country = '" . $country . "' and city_zipcode = '" . $zipcode . "';");
```
Vendor prod@addonline.fr mailed march 29th, no reply.
No online updates available.
=> Added Addonline_SoColissimo

magento1-vulnerable-extensions.csv
twitter.com/Acyba writes:
> We've released a lot of new version since this one. This has been released in version 2.2.1
> Unfortunately this is not available anymore as we stopped the plug-in development and we had to remove it from our website (La Poste asked us to do so)
=> Update fixed version number for Addonline_SoColissimo

src/ModuleBlacklist/Magerun/SecurityScanCommand.php, src/ModuleBlacklist/Magerun2/SecurityScanCommand.php
I tried to do a small change to the logic only.
Changes:
- when there are only potentially vulnerable modules (no known vulnerable modules), exit with status code 0 instead of 1
- use "info" style for message "Potential vulnerable module found: Foo_Bar" to differentiate from real errors. This results in a yellow-ish line, looking more like a warning (there is no `<warning>` for Symfony console output AFAIK).
Output and behaviour for known vulnerable modules stays the same.
=> Set exit code 0 for potentially vulnerable modules (fixes #39)

magento1-vulnerable-extensions.csv
Explained in https://xn--gran-8qa.fi/magento-1-raveinfosys-deleteorders-security-flaw/
=> Magento 1 Raveinfosys/DeleteOrders Security flaw

magento1-vulnerable-extensions.csv
There was no security announcement, but Mirasvit_Helpdesk has a "possible XSS security issue" up to 1.5.14: https://mirasvit.com/doc/extension_helpdesk/current/changelog
Note that MageVulnDb may report an older version for Mirasvit_Helpdesk than you actually have installed because a new marketing version might not trigger a change in `config.xml`. For example, marketing version 1.5.11 has the XML config entry `<version>1.0.36</version>`.
I will update this issue when I know if 1.5.14 has a newer XML config version.
=> Mirasvit_Helpdesk vulnerable up to version 1.5.14

magento2-vulnerable-extensions.csv
From https://github.com/gwillem/magevulndb/issues/37
Initial build out of the M2 vulnerable modules list. I pieced together info we've been given best I could.
Before merging, if possible:
Any attack URI info for any of the listed would also help -- and of course any additions are welcome.
=> Added initial known-vulnerable M2 modules (#37)

magento1-vulnerable-extensions.csv
See https://xn--gran-8qa.fi/magento-1-bl-customgrid-security-flaw/ for reference.
Will be providing later update url for fixed version. (I will fork this and provide update.)
Closes #28
=> Add BL_CustomGrid

README.md, magento1-vulnerable-extensions.csv
AheadWorks contacted me earlier today that they fixed the vulnerability in the latest version (2.5.1). They didn't mention it in their release notes but I downloaded it and have verified it is indeed fixed in this version.
=> Added fixed version for AheadWorks Autorelated

magento1-vulnerable-extensions.csv
Mico_Upload allows uploading of PHP code. It is exploited in the wild. 
Extension is encoded with IonCube. Vulnerability could be replicated using version 0.1.0. [Changelog](https://www.micosolutions.com/upload-ultimate-for-magento#changelog) does not mention security vulnerabilities so we have to assume the bug is present in the latest version. Vendor claims that the extension is not maintained anymore.
=> Add Mico_Upload

magento1-vulnerable-extensions.csv
Applies for all XTENTO import/export extensions. For example, see: https://www.xtento.com/xtcustom/changelog/show/module/Xtento_OrderExport/version/m1
=> Add Magento 1 XTENTO import/export extensions (Reflected XSS)

magento2-vulnerable-extensions.csv
Applies for all XTENTO import/export extensions. For example, see: https://www.xtento.com/xtcustom/changelog/show/module/Xtento_OrderExport/version/m2
=> Add Magento 2 XTENTO import/export extensions (Reflected XSS)

magento1-vulnerable-extensions.csv
This problem is since 1.1.0 and is sitting quietly for 3 years...
Via Magento 1 System / Configuration, it's possible to inject modified serialized data and when the next API call will be made,  the unserialize function will be executed on a specially crafted string, this will make a shop vulnerable for PHP Object Injection.
API Endpoint are protected with a token, but hence you are already in Admin, this is a possibility to get full control over the Magento shop
=> Dealer4dealer Xcore >= 1.1.0 in M1

magento2-vulnerable-extensions.csv
Reverts sansecio/magevulndb#98
Reverting, FishPig has not released new version numbers, as the malware injection happened in its deployment pipeline.
This means that we cannot use version numbers to determine malicious code.
=> Revert "Fishpig appears hacked (#98)"

magento1-vulnerable-extensions.csv
File upload to Magento1 media directory via AHT_Advancedmedia extension.
Secure version unknown. Vendor unknown.
From access logs in dfir case:
```
198.167.192.5   -  2022-10-22T16:28:19Z "POST /index.php/advancedmedia/index/upload/ HTTP/1.1" 200 62 "" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0" 0.075 0.072
198.167.192.5   -  2022-10-22T16:28:30Z "GET /media/catalog/product/a/d/adramen.php HTTP/1.1" 200 689 "" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0" 0.000
```
Confirmed adramen.php was php backdoor.
Was able to reproduce file upload.
Vulnerable code in `app/code/local/AHT/Advancedmedia/controllers/IndexController.php`:
```
public function uploadAction(){
$tempFile = $_FILES['Filedata']['tmp_name'];
$targetPath = …
```
=> add AHT_Advancedmedia

magento2-vulnerable-extensions.csv
Unfortunately Campaigner doesn't have release notes, so I don't know what exact version it was fixed in.
I did however check with @mpchadwick what the issue was, and it was unsafe usage of unserialize in a public controller. 
Their latest version uses json decoding instead.
=> update campaigner fix version

magento2-vulnerable-extensions.csv
Hi there
I've never contributed here, so in case I made a mistake, let me know :)
This is about the ConnectPOS_Core module, which is part of a whole bunch of ConnectPOS suite of modules that are not available as open source. The source is hosted on github but is private.
We found out a couple of weeks ago, that the module has some REST endpoints they use for debugging, which allows them to see the following things from your Magento shop:
- the main `composer.json` file of the Magento shop
- all the version numbers of the various ConnectPOS modules
- all the files in `var/log`
- all the files in `var/report`
The big problem is that those endpoints where publicly available without any authentication.
After some back and forth with them, they fixed this in version 23.09.03 of their module, …
=> Added ConnectPOS_Core module as vulnerable module.
